config/routes.rb
Rails.application.routes.draw do
  resources :environments, :only => [:index, :create]

  root to: "environments#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/environment.rb
class Environment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_action :set_environment, only: [:show, :edit, :update, :destroy]

  # GET /environments
  # GET /environments.json
  def index
    @count = Environment.count
  end

  # GET /environments/1
  # GET /environments/1.json
  def show
  end

  # GET /environments/new
  def new
    @environment = Environment.new
  end

  # GET /environments/1/edit
  def edit
  end

  # POST /environments
  # POST /environments.json
  def create
    @environment = Environment.new(environment_params)

    respond_to do |format|
      if @environment.save
        format.html { redirect_to @environment, notice: 'Environment was successfully created.' }
        format.json { render :show, status: :created, location: @environment }
      else
        format.html { render :new }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /environments/1
  # PATCH/PUT /environments/1.json
  def update
    respond_to do |format|
      if @environment.update(environment_params)
        format.html { redirect_to @environment, notice: 'Environment was successfully updated.' }
        format.json { render :show, status: :ok, location: @environment }
      else
        format.html { render :edit }
        format.json { render json: @environment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /environments/1
  # DELETE /environments/1.json
  def destroy
    @environment.destroy
    respond_to do |format|
      format.html { redirect_to environments_url, notice: 'Environment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_environment
      @environment = Environment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def environment_params
      params.require(:environment).permit(:ip_address, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/environments_helper.rb
module EnvironmentsHelper
end

app/views/environments/_form.html.erb
<%= form_for(environment) do |f| %>
  <% if environment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(environment.errors.count, "error") %> prohibited this environment from being saved:</h2>

      <ul>
      <% environment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ip_address %>
    <%= f.text_field :ip_address %>
  </div>

  <div class="field">
    <%= f.label :data %>
    <%= f.text_field :data %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/environments/edit.html.erb
<h1>Editing Environment</h1>

<%= render 'form', environment: @environment %>

<%= link_to 'Show', @environment %> |
<%= link_to 'Back', environments_path %>

app/views/environments/index.html.erb
<h1>Environments</h1>

<h2><%= @count %></h2>

app/views/environments/new.html.erb
<h1>New Environment</h1>

<%= render 'form', environment: @environment %>

<%= link_to 'Back', environments_path %>

app/views/environments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ip address:</strong>
  <%= @environment.ip_address %>
</p>

<p>
  <strong>Data:</strong>
  <%= @environment.data %>
</p>

<%= link_to 'Edit', edit_environment_path(@environment) %> |
<%= link_to 'Back', environments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dump</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>